package edu.ufsj.lox;

enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
	COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,
	BANG, BANG_EQUAL,
	EQUAL, EQUAL_EQUAL,
	GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
	
	IDENTIFIER, STRING, NUMBER,
	
	//RESERVED KEYWORDS
	AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL,
	OR, PRINT, RETURN, SUPER, THIS, TRUE,
	VAR, WHILE,
    
    //END OF FILE
    EOF
}